# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReedCanaryProject
                                 A QGIS plugin
 2021-2022 CS46x Capstone project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-01
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Logan, Abhi, Nuocheng
        email                : Logan@kleditz.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from xml.etree.ElementTree import tostring
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QDockWidget
from qgis.core import QgsProject, Qgis
from qgis import processing
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import *
from PyQt5.QtCore import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .reed_canary_project_dialog import ReedCanaryProjectDialog
from .reed_canary_project_dialog import Test1Dialog
import os.path

temp_list = ["T:\\Teach\\Classes\\CS461\\ReedCanary\\Images\\pix4D_2019-04-03_transparent_reflectance_w550nm.tif"]
items_list = []
#filename = ""
class ReedCanaryProject:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ReedCanaryProject_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.dlg = ReedCanaryProjectDialog()
        self.dlg2 = Test1Dialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Reed Canary Project')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.toolbar = self.iface.addToolBar(u'&Reed Canary Project')
        self.toolbar.setObjectName(u'&Reed Canary Project')


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ReedCanaryProject', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/reed_canary_project/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'ReedCanaryProject2021'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Reed Canary Project'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_file4(self):
        filename, _filer = QFileDialog.getOpenFileName(self.dlg, "Open File", "nm", '*.tif')
        self.dlg.lineEdit_4.setText(filename)

    def refresh_listView(self):
        qListView = QDockWidget()
        model = QStandardItemModel()
        temp_array = []
        for layer in QgsProject.instance().layerTreeRoot().children():   
            if layer.name().find("nm") != -1:
                item = QStandardItem(layer.name())
                check = Qt.Checked
                item.setCheckState(check)
                item.setCheckable(True)
                model.appendRow(item)
                temp_array.append(layer.name())
        for i in temp_array:
            temp = QgsProject.instance().mapLayersByName(i)
            print("yes", QgsProject.instance().mapLayersByName(i))
            print(temp[0].dataProvider().dataSourceUri())
            items_list.append(temp[0].dataProvider().dataSourceUri())


        self.dlg.listView.setModel(model)
        self.dlg.listView.show()

        # show the dialog 

    def vraster(self):
        temp = self.dlg.lineEdit.text().replace('/', '\\')
        #print("temp", temp)
        
        temp = self.dlg.lineEdit.text()
        outfile = self.dlg.lineEdit.text() + ".vrt"
        #print("outputfile", outfile)
        #print(items_list)
        processing.run("gdal:buildvirtualraster", 
        {'INPUT':items_list,'RESOLUTION':0,'SEPARATE':True,'PROJ_DIFFERENCE':False,'ADD_ALPHA':False,'ASSIGN_CRS':None,'RESAMPLING':0,'SRC_NODATA':'',
        'OUTPUT':outfile})

    def dir_path(self, button):

        if button == 2:
            filename, _filter = QFileDialog.getSaveFileName(  
            self.dlg, "Select output filename and destination","new_virtualraster", 'FileAttribute')  
            self.dlg.lineEdit.setText(filename)
        else:
            filename, _filter = QFileDialog.getSaveFileName(  
            self.dlg, "Select output filename and destination","", '*.shp')
            self.dlg.lineEdit.setText(filename)
        #temp = self.dlg.lineEdit.text().replace('/', '\\')
        #print(self.dlg.lineEdit.text(), temp)




    def open_ui_2(self):
        print("hello")

        self.dlg2.show()

    def newshp(self):
        filename, _filter = QFileDialog.getSaveFileName(  
        self.dlg2, "Select output filename and destination","treatement-areas", '*.shp')  
        self.dlg2.lineEdit.setText(filename)


    def run(self,checked):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ReedCanaryProjectDialog()
            self.dlg.pushButton.clicked.connect(self.vraster)
            self.dlg.lineEdit.clear()
            self.dlg.pushButton_2.clicked.connect(self.dir_path, 2)
            self.dlg.pushButton_4.clicked.connect(self.dir_path, 4)
            self.dlg.pushButton_3.clicked.connect(self.open_ui_2)
            self.dlg2.pushButton.clicked.connect(self.newshp)

        items = self.refresh_listView()

        
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
